### ISSUE TITLE
Rasha Ali: Week 1, State

### ISSUE THREAD

**Issue by Rashaali84** [HackYourFutureBelgium/class-8#194]
### Prep Work

- [x] What is State?
- [x]     Stack Overflow
- [x] Objects & Arrays
- [x]     Reference vs. Value (Mosh video)
- [x]     Reference vs. Value (CodeBurst article)
- [x] DOM Manipulation
- [x]     DOM Tree (js.info)
- [x]     Walking the DOM (js.info)
- [x]     getElement & querySelector (js.info)
- [x] Sunday Lesson Plan

### biggest-and-smallest:

- [repository](https://github.com/Rashaali84/biggest-and-smallest)
- [live demo](https://rashaali84.github.io/biggest-and-smallest/)
- [x]  [step 1-listeners](https://github.com/Rashaali84/biggest-and-smallest/tree/listeners)
- [x]  [step 2-handlers](https://github.com/Rashaali84/biggest-and-smallest/tree/handlers)
- [x] [ReadMe.md](https://github.com/Rashaali84/biggest-and-smallest/blob/master/README.md)
- [x] [Development-strategy ](https://github.com/Rashaali84/biggest-and-smallest/blob/master/development-strategy.md)

### Exercises:
- [x] Isolating JavaScript
  Continue the FreeCodeCamp JavaScript exercises
  Sign into FreeCodeCamp using your GitHub Account
  Turn on your Public Profile
- [x] Complete Basic Data Structures
- [x] Begin Basic Algorithm Scripting

**Fork JS Exercises**
- [x] [Solve the Exercises in the folders called week-3, and week-3-practice.](url)
- [x] [Repo-week-3](https://github.com/Rashaali84/js-exercises/tree/master/week-3)
- [x] [Repo-week-3-practice](https://github.com/Rashaali84/js-exercises/tree/master/week-3-practise)
- [x] [Live](https://rashaali84.github.io/js-exercises/)

**Integrating JavaScript**
- [x] [Fork dom-manipulation](url)
- [x] [Repo](https://github.com/Rashaali84/dom-manipulation)
- [x] [Live](https://rashaali84.github.io/dom-manipulation/)

- [x]     **Fork listeners-and-handlers** solve all exercises .
          - [Live](https://rashaali84.github.io/listeners-and-handlers/)
          - [Repo](https://github.com/Rashaali84/listeners-and-handlers)

- [x]     **Fork handler-refactors** solve all exercises .
           - [Live](https://rashaali84.github.io/handler-refactors/)
          - [Repo](https://github.com/Rashaali84/handler-refactors)

![jjss](https://user-images.githubusercontent.com/30797974/75169228-7915c680-5728-11ea-9da1-6940e5d09689.png)

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.

**Comment by colevandersWands** [comment]
@Rashaali84, in your handlers you updated the UI using local variables instead of properties from the state object: https://github.com/Rashaali84/biggest-and-smallest/blob/99697a455891a07de4be7b423bf16169a28dd117/handlers/save-number.js#L14

right now this may not seem important, but imagine a more complicated application where many parts of the app are updating state all the time.  reading from local variables runs the risk of using out-dated information.  you should learn to treat the shared state object as the only source of truth

and getting extra picky, take a look through your development strategy and re-write it so the user-story steps are more like what you see in the stepped example: https://github.com/HackYourFutureBelgium/state/tree/master/example-projects/up-down-stepped This wasn't covered so thoroughly in class but i'm sure you can figure it out.  
there are also some guiding questions in here: https://github.com/HackYourFutureBelgium/state/blob/master/example-projects/searchable-dictionary-separated/development-strategy.md

a way to understand the relationship between development strategies from last module and ones from this module:
* last module, each development strategy described a single user story - to implement a user story you need to add a listener, handler, dom & logic
* in this module, you are making multiple user stories around one shared object.  so for each user story in this module you should specify which code you needed to add

**Comment by Rashaali84** [comment]
Hello Evan , Thank you for your comment .. I have made the updates as per your explanation  , can you please check them?

**Comment by colevandersWands** [comment]
@Rashaali84, that's it.  you're good to go!
