### ISSUE TITLE
mesutBE: Week 2, encapsulation

### ISSUE THREAD

**Issue by MesutBE** [HackYourFutureBelgium/class-8#263]
### Binding `this`

- [x] [Examples of `this` and bind](https://www.youtube.com/watch?v=PIkA60I0dKU)
- [x] Zach Gordon: [this](https://www.youtube.com/watch?v=2qMKjWf1KdE), [binding this](https://www.youtube.com/watch?v=73aAyap_88w), [example: event handlers](https://www.youtube.com/watch?v=sxRnmKldiBs)
- [x] [Binding example in JS Tutor](http://www.pythontutor.com/javascript.html#code=function%20returnThis%28%29%20%7B%0A%20%20return%20this%3B%0A%7D%0Aconst%20demo0%20%3D%20returnThis%28%29%3B%0A%0Aconst%20obj1%20%3D%20%7B%0A%20%20id%3A%201,%0A%20%20returnThis%0A%7D%3B%0Aconst%20demo1%20%3D%20obj1.returnThis%28%29%3B%0A%0Aconst%20obj2%20%3D%20%7B%20id%3A%202%20%7D%3B%0Aconst%20boundToObj2%20%3D%20returnThis.bind%28obj2%29%3B%0Aconst%20demo2%20%3D%20boundToObj2%28%29%3B%0A%0Aconst%20boundToLiteral%20%3D%20returnThis.bind%28%7B%20id%3A%203%20%7D%29%3B%0Aconst%20demo3%20%3D%20boundToLiteral%28%29%3B&curInstr=0&mode=display&origin=opt-frontend.js&py=js&rawInputLstJSON=%5B%5D)

### Isolate

- Binding this: [examples](../javascripting/binding-this-examples/REVIEW.md), [exercises](../javascripting/binding-this-exercises/REVIEW.md)
- Binding arguments: [examples](../javascripting/binding-arguments-examples/REVIEW.md), [exercises](../javascripting/binding-arguments-exercises/REVIEW.md)

### Integrate

- Bound Incrementor (example): [stepped](../example-projects/bound-incrementor-stepped), [separated](../example-projects/bound-incrementor-separated)
- [Entries w/ Binding Handlers](https://github.com/hackyourfuturebelgium/entries-binding-handlers) (starter repo)

---

#### Isolating JavaScript

Solve each exercise on a separate branch and merge to master when they are complete.  Be sure to run `$ node review.js` before pushing to make it easier for your coaches to review your work.

- [x] [es6-classes](https://github.com/hackyourfuturebelgium/es6-classes)
  :heavy_check_mark: :heavy_check_mark: :heavy_check_mark: :heavy_check_mark:
  [repo](https://github.com/MesutBE/es6-classes)
  [live](https://mesutbe.github.io/es6-classes/)
  [REVIEW](https://github.com/MesutBE/es6-classes/blob/master/literals-to-class/REVIEW.md)

#### Integrating JavaScript

- [x] [binding-handlers](https://github.com/hackyourfuturebelgium/binding-handlers)
  [live](https://mesutbe.github.io/binding-handlers/)
  [repo](https://github.com/MesutBE/binding-handlers)
- [x] Project Custom-Video-Player
  - [x] [repo](https://github.com/MesutBE/Custom-Video-Player)
  - [x] [live](https://mesutbe.github.io/Custom-Video-Player/)

#### Challenge Exercises

- (_Isolate_) [FCC Functional Programming](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/functional-programming/)
- (_Isolate_) [FCC Intermediate Algorithm Scripting](https://www.freecodecamp.org/learn/javascript-algorithms-and-data-structures/intermediate-algorithm-scripting/)
- (_Isolate_) [javascript-exercises](https://github.com/TheOdinProject/javascript-exercises)
- (_Isolate_) [js-exercises-tdd](https://github.com/CodeYourFuture/js-exercises-tdd)

### Project: `booklist-app`

>> [repo](https://github.com/MesutBE/booklist-app)
>>[live](https://mesutbe.github.io/booklist-app/)
- [x] [development-strategy.md](https://github.com/MesutBE/booklist-app/blob/master/development-strategy.md)
- [x] [Branches](https://github.com/MesutBE/booklist-app/branches)
  1. [Branch - DOM](https://github.com/MesutBE/booklist-app/tree/DOM)
  1. [Branch - data-Log](https://github.com/MesutBE/booklist-app/tree/data-Log)
  1. [Branch - add-book-display](https://github.com/MesutBE/booklist-app/tree/add-book-display)
  1. [Branch - add-book-from-input](https://github.com/MesutBE/booklist-app/tree/add-book-from-input)
  1. [Branch - delete-book](https://github.com/MesutBE/booklist-app/tree/delete-book)
  1. [Branch - validation-storage](https://github.com/MesutBE/booklist-app/tree/validation-storage)
  1. [Branch - master](https://github.com/MesutBE/booklist-app/tree/master)
- [x] The final code of the tutorial organized into separate files and folders.  It's up to you!  The only wrong answer is one .js file with all of your code ;)
- [x] [README](https://github.com/MesutBE/booklist-app/blob/master/README.md) 

---
---

**Comment by bramdevries** [comment]
**booklist-app**

[`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) is an  interesting Web API that you should look into for this project. It allows you to access fields of a form in an easier way without using `document.querySelector` so it means that https://github.com/Rashaali84/booklist-app/blob/master/interactions/add-book.js#L6-L9 can be refactored to:

```js
const formData = new FormData(e.target);

const title = formData.get('title');
const author = formData.get('author');
const isbn = formData.get('isbn');
```
---

One thing to be aware of is that when you introduce state to a UI you need to have a single source of truth (in this case it's your `Store` object) from which you can derive a UI. Currently it's a bit of a mix and match because in [add-book.js](https://github.com/Rashaali84/booklist-app/blob/master/interactions/add-book.js#L19) and [remove-book.js](https://github.com/Rashaali84/booklist-app/blob/master/interactions/remove-book.js#L5) you're handling UI concerns before adapting your state which could lead to bugs (what if an error occurs during those methods? Your state would no longer match).

My suggestion would be that instead of having those methods you'd change [`displayBooks`](https://github.com/Rashaali84/booklist-app/blob/master/views/user-interface.js) so that it always renders the entire set of books from scratch. So you're handlers would become:

```js
// add-book.js
Store.addBook(book);
UI.displayBooks();

// remove-book.js
Store.removeBook(e.target.parentElement.previousElementSibling.textContent);
UI.displayBooks();
```

This is called the [MVC](https://alistapart.com/article/javascript-mvc/) pattern and it's how a lot of applications are organized. 

An added benefit is that instead of having a single `UI` class you could make specific classes for each view (eg: `Books` and `Alert`).

*I know you based your project on the code-along video but I thought these were some nice improvements that you could explore on your own.*

**Comment by MesutBE** [comment]
Hi @bramdevries, thank you for your detailed review. Some of them is about @Rashaali84 's repository :smile:  but I will explore what it is about mine, no problem. I will upgrade them.

**Comment by bramdevries** [comment]
Yes it's the same because it's a code-along so the code is 90% the same between you two. These are simply some suggestions to help further explore the project and make it your own.

**Comment by MesutBE** [comment]
Hi @bramdevries,

> **booklist-app**
> 
> [`FormData`](https://developer.mozilla.org/en-US/docs/Web/API/FormData) is an interesting Web API that you should look into for this project. It allows you to access fields of a form in an easier way without using `document.querySelector` so it means that https://github.com/Rashaali84/booklist-app/blob/master/interactions/add-book.js#L6-L9 can be refactored to:
> 
> ```js
> const formData = new FormData(e.target);
> 
> const title = formData.get('title');
> const author = formData.get('author');
> const isbn = formData.get('isbn');
> ```
> 
I couldn't update my code with this way. It always returns null. I tried to find a solution from https://developer.mozilla.org/en-US/docs/Web/API/FormData, https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects, stackoverflow.

**Comment by bramdevries** [comment]
To use `FormData` you need to make sure all your `input` elements have a `name` attribute.

**Comment by MesutBE** [comment]
Thank you for tips @bramdevries, I updated all your suggestions.
