### ISSUE TITLE
Katia: Working on Code, week 1

### ISSUE THREAD

**Issue by KLisabeth** [HackYourFutureBelgium/class-8#8]
## My First Homework

- [x] (computer) Software Installations
  - [x] [Chromium](https://download-chromium.appspot.com/), [Firefox](https://www.mozilla.org/en-US/firefox/developer/) or [Brave](https://brave.com/download/): All great browsers with ES6, HTML5 & CSS3 support plus pre-installed, top-knotch developer tools.  Try each one to see what you like best!
  - [x] [Visual Studio Code](https://code.visualstudio.com/download): Like Microsoft Word, but for code ...  and _sooooo_ much better.  After installing VSC, be sure to install these plug-ins:
    - [x] [Markdown Preview Github Styling Custom](https://marketplace.visualstudio.com/items?itemName=dmodalek.markdown-preview-github-styles-custom)
    - [x] [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker)
    - [x] [Prettier](https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode#overview)
  - [x] [GitKraken](https://www.gitkraken.com/download): A program that will help you master using git.
  - [x] (If you have windows) [Git For Windows](https://gitforwindows.org/): This will allow you to use the same terminal commands & tools as Linux or Mac computers.
- [x] (computer) Start an HYF Directory
- [x] [My bio on the class repo](https://github.com/hackyourfuturebelgium/class-7/blob/master/student-bios/<your-user-name>.md)
- [x] [Hack My Future](https://github.com/<your-user-name>/hack-my-future)
- [x] [Markdown Home Page](<your-user-name>.github.io) - my multi-page markdown home portfolio, live on github pages

**Comment by KLisabeth** [comment]
finished

**Comment by KLisabeth** [comment]
*What exactly am I suppose to write here? A code or a comment?

**Comment by colevandersWands** [comment]
add it to this week's project board and move it into the "DONE" column, only then I will know you're ready for review. 

> because I have a very short memory and already forgot you said you were finished

**Comment by colevandersWands** [comment]
Almost there, soooo close.  Open the project board and you'll see `+ Add cards` at the top right.  

Click and drag your issue into the DONE column and then I can check you off

**Comment by KLisabeth** [comment]
thank you!

**Comment by KLisabeth** [comment]
think I have to work on my project and write some code and add a picture on Work on code project, so will continue a bit

**Comment by colevandersWands** [comment]
@KLisabeth , one of us should actually close your issues and move them to the "DONE" column.

You can move it as far as "READY FOR REVIEW" but it is up to a coach or alumni to give you the final check-off.  That's my bad.  I see I'd told you to do that yourself up there ^

In this case I see that you actually haven't done any of the assignments completely, something you wouldn't be able to catch yourself.

* I see you added your student-bio by editing directly our fork.  I can see that because your fork does not have your bio, and there is no closed pull request from you on this repo.
* your `hack-my-future` repo is still missing the project board
* you need to rename your portfolio site. You'll know this one is complete when https://KLisabeth.github.io is a working site

You can find more detailed instructions for the assignments [in the module repo](https://github.com/HackYourFutureBelgium/working-with-code/blob/master/week-1/README.md), and the [student-bios folder](https://github.com/hackyourfuturebelgium/class-8/tree/master/student-bios) has more instructions on how to do a pull request
