### ISSUE TITLE
Feruzteame: Week 2, Incremental development

### ISSUE THREAD

**Issue by Feruzteame** [HackYourFutureBelgium/class-8#99]
## Prep Work

- [x] Inspecting the DOM
- [x] HTML & CSS
- [x] Code Review
- [x] Git, GitHub & GitKraken

### Code-Along:

- [repository](https://github.com/Feruzteame/app-theme)
- [live](https://feruzteame.github.io/app-theme/home.html)
- [x]  step 1: creat README.md [README.md](https://github.com/Feruzteame/app-theme/blob/master/README.md)
- [x]  step 2:  creat development-strategy.md [development-stratgey.md](https://github.com/Feruzteame/app-theme/blob/master/development%20strategy.md)
- [x]  step 3: create repo
- [x]  step 4: create an issue
- [x] step 5: move to the project board
- [x] step 6: open and study the Responsive Template tutorial.
- [x] step 7: work in your repo 

### Exercises:

- [x] Responsive Web Design Principles  [Account]( https://www.freecodecamp.org/learn)
- [x] HTML-CSS-Practice-Problems [live](https://feruzteame.github.io/HTML-CSS-Practice-Problems/level-2/index.html)
- [ ] css-exercise

> [Follow this link](https://github.com/HackYourFutureBelgium/class-6/issues/59) to study a well-done homework issue.
-------------------------------------

##  Html- Css practice problem

![Screenshot 2020-01-21 at 08 47 01](https://user-images.githubusercontent.com/59234162/73052925-adc30380-3e86-11ea-873a-037d663451ce.png)
-----------------------------------------

## Responsive web Design principle

![Screenshot 2020-01-21 at 07 23 53](https://user-images.githubusercontent.com/59234162/73052873-7fddbf00-3e86-11ea-9b94-1587c76f7299.png)
-----------------------------------

## Gitkraken branch for the project

![Screenshot 2020-01-24 at 08 56 12](https://user-images.githubusercontent.com/59234162/73053293-a6502a00-3e87-11ea-97f5-c31107ef071c.png)

**Comment by otagi** [comment]
Good user stories! Try to use more descriptive and unique names in the `Step` column. For example, instead of `style.css`, you can name them `About Style`, `Service Style`, etc. These can then be used as your branch names as well.

The HTML code looks good. Some indentation are slightly off, but you got the general concept right. 👍 

The CSS code is correct, but the formatting could be improved by putting the selector and the properties on separate lines, like this:

```css
#image {
  height: 300px;
  width: 500px;
}
```

It will be a bit easier to read that way.

Don't hesitate to ask more questions about git on Sunday, and to do more exercises with branches at home, so that you get more comfortable with them.
